name: SOE Catalog - Bug Report
description: Use this issue template to report bugs in the State of the Ecosystem indicator catalog.
title: "[Bug Report]: "
labels: ["bug"]
assignees: "BBeltz1"
body:
  - type: markdown
    attributes:
      value: |
        Please use the fields below to identify the bug and provide related information we can use to troubleshoot. Thanks.
  - type: input
    id: contact1
    attributes:
      label: Primary Contact
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@noaa.gov
    validations:
      required: true
